### ISSUE TITLE
issue with send message button in Support section

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/critical-css-for-wp#28]
When clicking on send afterr writing message, it doesn't show if message is sent or failed.

**Comment by akshaywali** [comment]
Confirmation should display after sending message   https://github.com/ahmedkaludi/critical-css-for-wp/commit/a5e5c54496652d61ffa8e228b09a24672313ea76

**Comment by akshaywali** [comment]
pushed in update 1.0.9
